from sqlalchemy import Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import relationship

from app.database import Base


# ============================================================
# ROLE MODEL
# ============================================================
# Purpose:
# This table stores user roles in the system.
#
# Example roles:
# 1. super_admin  -> Owner / full access
# 2. admin        -> Manager / operational access
# 3. agent        -> Member / sales person
#
# This will be used for backend role-based access control.

class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)

    # Role name must be unique.
    # Example: super_admin, admin, agent
    name = Column(String, unique=True, nullable=False, index=True)

    # Optional explanation of the role.
    description = Column(String)


# ============================================================
# USER MODEL
# ============================================================
# Purpose:
# This table stores login users.
#
# Important:
# User is different from Agent/Member.
#
# Example:
# - Super Admin is a user but may not be an agent.
# - Admin is a user but may not be an agent.
# - Agent login user can be connected to an Agent record using agent_id.
#
# Login will happen using:
# email + password
#
# Password will not be stored directly.
# We will store hashed_password only.

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)

    # Login user basic details
    name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False, index=True)

    # Never store plain password.
    # Store only hashed password generated by passlib/bcrypt.
    hashed_password = Column(String, nullable=False)

    # Role reference:
    # user.role_id -> roles.id
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False)

    # Optional agent/member reference:
    # Only agent users will have agent_id.
    # Super Admin/Admin can keep this NULL.
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=True)

    # User account status:
    # Active / Inactive / Blocked
    status = Column(String, default="Active")

    # Date fields stored as string for now.
    # Later we can improve this to DateTime.
    created_date = Column(String)
    last_login = Column(String)

    # Relationships
    role = relationship("Role")
    agent = relationship("Agent", foreign_keys=[agent_id])


# ============================================================
# AGENT / MEMBER MODEL
# ============================================================
# Purpose:
# This table stores business members/agents.
#
# Members bring printing jobs/orders from customers.
#
# Hierarchy:
# Company
#   └── Direct Member
#         └── Child Member
#               └── Grandchild Member
#
# parent_agent_id stores who hired this member.
#
# Example:
# Ravi hires Sibu.
# Sibu.parent_agent_id = Ravi.id

class Agent(Base):
    __tablename__ = "agents"

    id = Column(Integer, primary_key=True, index=True)

    # Unique member code like AG001, AG002
    code = Column(String, unique=True, index=True)

    # Basic member details
    name = Column(String, nullable=False, index=True)
    email = Column(String, unique=True, index=True)
    phone = Column(String)
    address = Column(String)

    # Parent member ID for hierarchy.
    # If NULL, this member is directly under company.
    parent_agent_id = Column(Integer, ForeignKey("agents.id"), nullable=True)

    # Member business summary
    total_orders = Column(Integer, default=0)
    total_commission = Column(Float, default=0)
    printing_revenue = Column(Float, default=0)

    # Member status:
    # Active / Inactive
    status = Column(String, default="Active")
    joined_date = Column(String)

    # Self relationship for parent-child hierarchy.
    # This allows us to find parent member details.
    parent = relationship("Agent", remote_side=[id])


# ============================================================
# ORDER / JOB MODEL
# ============================================================
# Purpose:
# This table stores printing jobs/orders.
#
# One job contains:
# - Customer details
# - Product details
# - Requirement costing
# - Printing cost
# - Member commission chain
# - Job status
#
# Important:
# Commission is calculated from printing_cost.
#
# Total job amount is calculated from:
# Paper + Plate + Printing + Lamination + Binding

class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)

    # ========================================================
    # BASIC JOB DETAILS
    # ========================================================

    # Public job/order code like ORD-1001
    order_id = Column(String, unique=True, index=True)

    # Customer and product information
    customer_name = Column(String, nullable=False)
    product_name = Column(String, nullable=False)

    # Quantity and price details
    quantity = Column(Integer, nullable=False)
    unit_price = Column(Float, nullable=False)

    # Total customer/job amount
    total_amount = Column(Float, nullable=False)

    # Printing cost is used for commission calculation
    printing_cost = Column(Float, nullable=False)

    # ========================================================
    # JOB REQUIREMENT COSTING FIELDS
    # ========================================================
    # These fields store the 5 major printing job cost parts:
    #
    # 1. Paper
    # 2. Plate
    # 3. Printing
    # 4. Lamination
    # 5. Binding
    #
    # Admin/Super Admin can manually enter type and amount.

    paper_type = Column(String, nullable=True)
    paper_amount = Column(Float, default=0)

    plate_type = Column(String, nullable=True)
    plate_amount = Column(Float, default=0)

    printing_type = Column(String, nullable=True)
    printing_amount = Column(Float, default=0)

    lamination_type = Column(String, nullable=True)
    lamination_amount = Column(Float, default=0)

    binding_type = Column(String, nullable=True)
    binding_amount = Column(Float, default=0)

    # Sum of all 5 requirement amounts:
    # paper_amount + plate_amount + printing_amount
    # + lamination_amount + binding_amount
    requirement_total_amount = Column(Float, default=0)

    # ========================================================
    # MEMBER / AGENT COMMISSION CHAIN
    # ========================================================
    # This freezes the commission hierarchy at job creation time.
    #
    # Example:
    # Direct Member = Sibu
    # Parent Member = Ravi
    # Grandparent Member = Amit
    #
    # Even if hierarchy changes later, old job commission remains safe.

    direct_agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)
    parent_agent_id = Column(Integer, ForeignKey("agents.id"), nullable=True)
    grandparent_agent_id = Column(Integer, ForeignKey("agents.id"), nullable=True)

    # Commission values:
    #
    # direct_agent_commission:
    # Original direct commission before deduction.
    #
    # parent_commission:
    # Commission paid to parent member.
    #
    # grandparent_commission:
    # Commission paid to grandparent member.
    #
    # final_direct_agent_commission:
    # Final amount payable to direct member after deducting parent/grandparent share.

    direct_agent_commission = Column(Float, default=0)
    parent_commission = Column(Float, default=0)
    grandparent_commission = Column(Float, default=0)
    final_direct_agent_commission = Column(Float, default=0)

    # ========================================================
    # JOB STATUS AND DATES
    # ========================================================
    # Status values:
    # Pending / Running / Completed

    status = Column(String, default="Pending")
    delivery_date = Column(String)
    created_date = Column(String)

    # ========================================================
    # OLD PAYMENT FIELDS
    # ========================================================
    # These fields were added earlier when payment was stored
    # directly inside orders table.
    #
    # We are keeping them for backward safety.
    #
    # Correct new payment module uses:
    # CommissionPayment table below.
    #
    # Do not use these fields for new payment logic.

    agent_paid_amount = Column(Float, default=0)
    payment_status = Column(String, default="Pending")
    payment_date = Column(String)
    payment_method = Column(String)

    # Relationship with direct member/agent
    direct_agent = relationship("Agent", foreign_keys=[direct_agent_id])


# ============================================================
# COMMISSION PAYMENT MODEL
# ============================================================
# Purpose:
# This table stores company-to-member commission payments.
#
# This is the correct payment module.
#
# One job can create multiple payment records:
#
# Example:
# Job ORD-1001
#
# Direct Member payment:
#   Sibu -> ₹925
#
# Parent Member payment:
#   Ravi -> ₹50
#
# Grandparent Member payment:
#   Amit -> ₹25
#
# Each payment row can be:
# Pending / Partial / Paid

class CommissionPayment(Base):
    __tablename__ = "commission_payments"

    id = Column(Integer, primary_key=True, index=True)

    # Unique payment code like PAY-1001, PAY-1002
    payment_id = Column(String, unique=True, index=True)

    # ========================================================
    # JOB / ORDER REFERENCE
    # ========================================================

    # Internal database order id
    order_db_id = Column(Integer, ForeignKey("orders.id"), nullable=False)

    # Public order code like ORD-1001
    order_id = Column(String, nullable=False)

    # ========================================================
    # MEMBER / AGENT PAYMENT RECEIVER
    # ========================================================

    # Member who will receive this commission payment
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)
    agent_name = Column(String, nullable=False)

    # Example values:
    # Direct Member
    # Parent Member
    # Grandparent Member
    agent_role = Column(String, nullable=False)

    # ========================================================
    # PAYMENT AMOUNTS
    # ========================================================

    # Actual commission company has to pay to this member
    commission_amount = Column(Float, default=0)

    # Amount company already paid
    paid_amount = Column(Float, default=0)

    # Remaining amount company has to pay
    pending_amount = Column(Float, default=0)

    # Payment status:
    # Pending  -> paid_amount = 0
    # Partial  -> 0 < paid_amount < commission_amount
    # Paid     -> paid_amount = commission_amount
    payment_status = Column(String, default="Pending")

    # Payment info
    payment_date = Column(String)
    payment_method = Column(String)

    # Date tracking
    created_date = Column(String)
    updated_date = Column(String)

    # Relationships
    order = relationship("Order", foreign_keys=[order_db_id])
    agent = relationship("Agent", foreign_keys=[agent_id])